### ISSUE TITLE
Wrong usage of '==' for value comparison 

### ISSUE THREAD

**Issue by atillier** [sportingsolutions/SS.Integration.UnifiedDataAPIClient.Java#17]
In your [StreamListener.java](https://github.com/sportingsolutions/SS.Integration.UnifiedDataAPIClient.Java/blob/049c694202bb6ef47bde21242088e9832be7f952/src/test/ss/udapi/sdk/examples/StreamListener.java#L153) code you wrongly use '==' when comparing Integer values. 

Due to autoboxing caveats the comparison works up to '127' but any Epoch greater than this would not match anymore. 
This has proven to be breaking update processing for event priced for a long time (like american sports).

You should use equals() instead.

**Comment by jswainston** [comment]
Thanks. I have pushed a change.
